### ISSUE TITLE
Kiosk dashboard.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Ragnarok#14]
The kiosk has currently no dashboard implemented. Before we release the first beta for this boilerplate we need to build up an kiosk management dashboard. Maybe if someone has time he can pick it up for hacktoberfest. Thats why we assign the label to it.

**Comment by testerslol123** [comment]
Can I know how to operate this? 
Currently I just do the seeding and didn't know what is login username and password.
May I take this project? Also I want to know about what kind of feature this offer?

I may create some dashboard based on feature that available.

Thank you.

**Comment by Tjoosten** [comment]
Hey @testerslol123 

Sorry for not giving that directly my fault. 

The seeds coming with 3 logins. 

**U:** webmaster@domain.tld 
**P:** password

**U:** developer@domain.tld**
**P:** password

**U:** user@domain.tld**
**P:** passwors

**Comment by Tjoosten** [comment]
Not closing this one because i will bring in some design changes
