### ISSUE TITLE
Document default users in the readme.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Ragnarok#15]
After creating ticket #14. 

I forgot to give the default user logins with the issue. So maybe it would be better to document them in the projects readme till there is a proper documentation portal.

**Comment by testerslol123** [comment]
Can I do the documentation login first? 
Before doing the other documentation?

Thanks

**Comment by Tjoosten** [comment]
Hey Tester, 

Sure. No problem. If you want to do it just do it 👍. 
I will assign u then on the issue.

**Comment by testerslol123** [comment]
Could you add hacktoberfest in label? It would helpful.

I also added documentation in how to operate this repo. 

Thanks

**Comment by Tjoosten** [comment]
Done!

**Comment by testerslol123** [comment]
#17 I just updated the pull request to here.

Can you review then, if something missing could tell me,
Thank you

**Comment by Tjoosten** [comment]
Will review it after my lunch break.
