### ISSUE TITLE
Untested policy methods in the user policy.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Ragnarok#4]
For now there are are 2 untested policy methods in the user policies. While these should be tested. 

- restoreUser 
- changePassword

**Comment by armsasmart** [comment]
Assign to me, please.

**Comment by Tjoosten** [comment]
Hey @armsasmart 

Ty for the intrest in this one. You are now assigned. If you have any questions feel free to ask!

**Comment by armsasmart** [comment]
Thank you. 

Do you have a contribution guide? 

Do I have to create a branch from develop ?

**Comment by Tjoosten** [comment]
No i have currently no contribution guide for now. It is planned to do after the role controller test that i currently working on. 

But yes of you want u can create a branch from develop. Although some tests can fail because the Faker directory i guess. Just simply re-run the tests.

**Comment by armsasmart** [comment]
ok thank ♥

**Comment by armsasmart** [comment]
@Tjoosten  I'm done. 🎉

**Comment by Tjoosten** [comment]
> @Tjoosten I'm done. 🎉

Ty. But will communicate further in the PR. If you don't mind. But very much thanks for your effort on this one.
